### PR TITLE
Fix/wgpu/tanh

### LINKED ISSUE #1086: tanh_should_not_have_numerical_bugs_on_macos is failing on MacOS
**Describe the bug**
```
failures:

---- kernel::unary::tests::tanh_should_not_have_numerical_bugs_on_macos stdout ----
thread 'kernel::unary::tests::tanh_should_not_have_numerical_bugs_on_macos' panicked at burn-wgpu/src/kernel/unary.rs:260:9:
assertion failed: !zero.is_nan() && zero == 1.0


failures:
    kernel::unary::tests::tanh_should_not_have_numerical_bugs_on_macos

test result: FAILED. 1238 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 14.63s

error: test failed, to rerun pass `-p burn-wgpu --lib`

```
**To Reproduce**
`./run-checks all` 

**Desktop (please complete the following information):**
 ```
[burn]$ uname -a
Darwin MacBook-Pro-Max.attlocal.net 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:33:00 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T6031 arm64
[burn]$

### PR DESCRIPTION
**Pull request by louisfd**
Fix #1086

### CODE REVIEW

File: burn-wgpu/src/codegen/function.rs [hunk 1]
```diff
@@ -6,13 +6,15 @@ use std::fmt::Display;
 pub enum Function {
     Powf(Elem),
     Erf(Elem),
+    SafeTanh(Elem),
```
Comment (nathanielsimard) [inline burn-wgpu/src/codegen/function.rs:9]: Add a feature flag for macos

**Review by nathanielsimard — CHANGES_REQUESTED** [review]

**Review by nathanielsimard — APPROVED** [review]
