### PR TITLE
Fix/conv2d docs display

### LINKED ISSUE #3509: Conv2d's Display impl should report input and output channels.
### Feature description

Conv2d's Display implementation should report the number of input and output channels for the layer. 

### Feature motivation

Debugging of convolutional neural networks would be easier.
Consistency with Linear's Display implementation that shows d_input and d_output.

### (Optional) Suggest a Solution

```rust 

impl<B: Backend> ModuleDisplay for Conv2d<B> {
    fn custom_settings(&self) -> Option<DisplaySettings> {
        DisplaySettings::new()
            .with_new_line_after_attribute(false)
            .optional()
    }

    fn custom_content(&self, content: Content) -> Option<Content> {
        // Since padding does not implement ModuleDisplay, we need to format it manually.
        let padding_formatted = format!("{}", &self.padding);

        // Format the stride, kernel_size and dilation as strings, formatted as arrays instead of indexed.
        let stride = format!("{:?}", self.stride);
        let kernel_size = format!("{:?}", self.kernel_size);
        let dilation = format!("{:?}", self.dilation);
        let [channels_out, group_channels_in, _kernel_size, __kernel_size] = self.weight.dims();
        let channels_in = group_channels_in * &self.groups;
        let ch_out = format!("{:?}", channels_out);
        let ch_in = format!("{:?}", channels_in);
        content
            .add("ch_in", &ch_in)
            .add("ch_out", &ch_out)
            .add("stride", &stride)
            .add("kernel_size", &kernel_size)
            .add("dilation", &dilation)
            .add("groups", &self.groups)
            .add("padding", &padding_formatted)
            .optional()
    }
}
```

I haven't tested it; I may be wrong about the relationship with the channel groups.

### PR DESCRIPTION
**Pull request by huy209vn**
### Checklist
- [x] Confirmed that `cargo run-checks` command has been executed.
- [x] Made sure the book (`model.md`) is up to date with changes in this PR.

### Related Issues/PRs
Fixes #3509

### Changes
- `Conv2d` Display now includes `ch_in` and `ch_out` (consistent with `Linear` showing `d_input`/`d_output`).
- Added doctest examples for `Conv2d::forward` and `Display` (feature-gated for `ndarray`).
- **Book**: updated `Model { ... }` example in `model.md` to reflect the new `Conv2d` Display output.  
  >code adapted from the issue reporter in #3509.

### Testing
Backend-agnostic check (Display derives from `weight.dims` + groups, so it should behave the same on any backend):
Ndarray example:
use burn::backend::ndarray::NdArray;
use burn::nn::conv::Conv2dConfig;

type B = NdArray;

fn main() {
    let device = Default::default();
    let conv = Conv2dConfig::new([3, 8], [3, 3]).init::<B>(&device);
    println!("{}", conv);
}
Output: Conv2d {ch_in: 3, ch_out: 8, stride: [1, 1], kernel_size: [3, 3], dilation: [1, 1], groups: 1, padding: Valid, params: 224}
WGPU example:

use burn::backend::wgpu::Wgpu;
use burn::nn::conv::Conv2dConfig;
use burn::tensor::{backend::Backend, Tensor};

type B = Wgpu<f32, i64>;

fn main() {
    let device = <B as Backend>::Device::default();
    let conv = Conv2dConfig::new([3, 8], [3, 3]).init::<B>(&device);
    println!("{}", conv);

    let x = Tensor::<B, 4>::zeros([1, 3, 32, 32], &device);
    let y = conv.forward(x);
    println!("Output dims: {:?}", y.dims());
}
Output:
Conv2d { ch_in: 3, ch_out: 8, stride: [1, 1], kernel_size: [3, 3], dilation: [1, 1], groups: 1, padding: Valid, params: 224 }
Output dims: [1, 8, 30, 30]

### CODE REVIEW

File: crates/burn-core/src/nn/conv/conv2d.rs [hunk 1]
```diff
@@ -114,6 +114,22 @@ impl Conv2dConfig {
...
+    ///
+    /// let device = Default::default();
+    /// let conv = Conv2dConfig::new([3, 8], [3, 3]).init::<NdArray>(&device);
+    ///
+    /// // Print Conv2d layer information using Display
+    /// println!("{}", conv);
+    /// # }
+    /// # #[cfg(not(feature = "ndarray"))]
+    /// # fn main() {}
+    /// ```
```
Comment (antimora) [inline crates/burn-core/src/nn/conv/conv2d.rs]: I don't this example is needed because the method is implementing a trait and we have loads of this else. It would have been helpful in public APIs.

File: crates/burn-core/src/nn/conv/conv2d.rs [hunk 2]
```diff
@@ -128,8 +144,13 @@ impl<B: Backend> ModuleDisplay for Conv2d<B> {
         let stride = format!("{:?}", self.stride);
         let kernel_size = format!("{:?}", self.kernel_size);
         let dilation = format!("{:?}", self.dilation);
-
+        let [channels_out, group_channels_in, _kernel_size, __kernel_size] = self.weight.dims();
```
Comment (antimora) [inline crates/burn-core/src/nn/conv/conv2d.rs]: Suggestion: [channels_out, group_channels_in, _kernel_size, __kernel_size] => [channels_out, group_channels_in, _, _] or [channels_out, group_channels_in, _kernel_size0, _kernel_size1]

File: crates/burn-core/src/nn/conv/conv2d.rs [hunk 3]
```diff
@@ -145,9 +166,32 @@ impl<B: Backend> Conv2d<B> {
     /// See [conv2d](crate::tensor::module::conv2d) for more information.
     ///
     /// # Shapes
+    /// - `input`: `[batch_size, channels_in, height_in, width_in]`
+    /// - `output`: `[batch_size, channels_out, height_out, width_out]`
+    ///
+    /// # Example
+    /// ```rust
```
Comment (antimora) [inline crates/burn-core/src/nn/conv/conv2d.rs]: I would just use `rust,ignore` not to force running instead of using `#[cfg(feature = "ndarray")]` tricks

@laggui, we should probably unify how we come up with examples. Probably use `B` for backends, etc. I don't have a strong opinion.

File: crates/burn-core/src/nn/conv/conv2d.rs (hunk 1 above)
Comment (huy209vn) [reply crates/burn-core/src/nn/conv/conv2d.rs]: so should i delete it?

File: crates/burn-core/src/nn/conv/conv2d.rs (hunk 3 above)
Comment (laggui) [reply crates/burn-core/src/nn/conv/conv2d.rs]: Agreed, I think marking as `ignore` and using `B` for backends is a good way to keep it generic while still being helpful.

File: crates/burn-core/src/nn/conv/conv2d.rs [hunk 4]
```diff
@@ -145,9 +150,23 @@ impl<B: Backend> Conv2d<B> {
...
+    /// let device = Default::default();
+    /// let conv = Conv2dConfig::new([3, 8], [3, 3]).init::<NdArray>(&device);
+    ///
+    /// let x = Tensor::<NdArray, 4>::zeros([1, 3, 28, 28], &device);
+    /// let y = conv.forward(x);
     ///
-    /// - input: `[batch_size, channels_in, height_in, width_in]`
-    /// - output: `[batch_size, channels_out, height_out, width_out]`
+    /// println!("{:?}", y.dims()); // [1, 8, 26, 26]
+    /// ```
```
Comment (laggui) [inline crates/burn-core/src/nn/conv/conv2d.rs]: Even if it's just an example, I would remove the explicit `NdArray` backend usage and instead demonstrate as if we had a type alias `B` or `MyBackend`

Comment (huy209vn) [reply crates/burn-core/src/nn/conv/conv2d.rs]: did so in [style: cargo fmt (Conv1d/2d/3d docs + display)](https://github.com/tracel-ai/burn/pull/3586/commits/44d03d2592cd02be6d5926c5cfd2c1279c88d754)

**Comment by huy209vn** [comment]
Hi, I’ve pushed the requested changes. Could you please take another look when you have time?

**Review by antimora — APPROVED** [review]
LGTM.

Thank you for your contribution!

File: crates/burn-core/src/nn/conv/conv2d.rs [hunk 5]
```diff
@@ -145,9 +150,25 @@ impl<B: Backend> Conv2d<B> {
...
+    /// - `output`: `[batch_size, channels_out, height_out, width_out]`
+    ///
+    /// # Example
+    /// ```rust,ignore
+    /// use burn::nn::conv::Conv2dConfig;
+    /// use burn::tensor::Tensor;
+    ///
+    /// // Choose your backend for B (e.g., burn::backend::ndarray::NdArray)
+    /// type B = burn::backend::ndarray::NdArray;
+    ///
```
Comment (laggui) [inline crates/burn-core/src/nn/conv/conv2d.rs]:
```suggestion
    /// // Assuming backend type alias `B`
```
