### PR TITLE
Use `ScalarIr` to represent scalars generically

### LINKED ISSUE #3659: Fusion backend limits size of multiplication scalars
**Describe the bug**

When the fusion backend is used, the value of scalars must fit in `i32` otherwise the code panics.

**To Reproduce**

`Cargo.toml` (removing the `fusion` feature flag and the code won't panic):

```toml
[package]
name = "tt-gpgpu"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.18.0", default-features = false, features = ["metal", "fusion"] }
```

`main.rs`:

```rust
use burn::backend::Wgpu;
use burn::tensor::{Distribution, Int, Tensor};

type Backend = Wgpu<f32, i64>;

fn main() {
    let device = Default::default();
    let input = Tensor::<Backend, 1, Int>::random([1], Distribution::Default, &device);

    // works
    let result = input.clone().mul_scalar(i32::MAX);
    println!("{result}");

    // panics when Fusion is used
    let result = input.mul_scalar(i32::MAX as u64 + 1);
    println!("{result}");
}
```

Output:
```
Tensor {
  data:
[431644213047],
  shape:  [1],
  device:  DefaultDevice,
  backend:  "fusion<cubecl<wgpu<msl>>>",
  kind:  "Int",
  dtype:  "i64",
}

thread 'main' panicked at /Users/hack/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/burn-tensor-0.18.0/src/tensor/element/cast.rs:208:1:
Element cannot be represented in the target type
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:75:14
   2: <i64 as burn_tensor::tensor::element::cast::ToElement>::to_i32
             at /Users/hack/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/burn-tensor-0.18.0/src/tensor/element/cast.rs:146:17
   3: <i32 as burn_tensor::tensor::element::base::ElementConversion>::from_elem
             at /Users/hack/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/burn-tensor-0.18.0/src/tensor/element/base.rs:137:17
   4: <i64 as burn_tensor::tensor::element::base::ElementConversion>::elem
             at /Users/hack/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/burn-tensor-0.18.0/src/tensor/element/base.rs:141:17
   5: burn_fusion::ops::int::<impl burn_tensor::tensor::ops::int_tensor::IntTensorOps<burn_fusion::backend::Fusion<B>> for burn_fusion::backend::Fusion<B>>::int_mul_scalar
             at /Users/hack/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/burn-fusion-0.18.0/src/ops/int.rs:979:18
   6: <burn_tensor::tensor::api::kind::Int as burn_tensor::tensor::api::numeric::Numeric<B>>::mul_scalar
             at /Users/hack/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/burn-tensor-0.18.0/src/tensor/api/numeric.rs:3460:9
   7: burn_tensor::tensor::api::numeric::<impl burn_tensor::tensor::api::base::Tensor<B,_,K>>::mul_scalar
             at /Users/hack/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/burn-tensor-0.18.0/src/tensor/api/numeric.rs:277:19
   8: tt_gpgpu::main
             at ./src/main.rs:13:18
   9: core::ops::function::FnOnce::call_once
             at /Users/hack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Expected behavior**

Multiplying by a constant larger than `i32::MAX` shouldn't panic when the `fusion` backend is used. The issue seems to be the use of [i32 for the numeric operation](https://github.com/tracel-ai/burn/blob/f5fe97895ce8d7e67b53f684f66474091ccbf467/crates/burn-ir/src/operation.rs#L71).

### PR DESCRIPTION
**Pull request by laggui**
### Checklist

- [ ] Confirmed that `cargo run-checks` command has been executed.

### Related Issues/PRs

Fixes #3659

### Changes

Scalar operations in the IR were hardcoded to a single primitive type, which had a couple of limitations (among others, the linked issue).

This PR introduces a `ScalarIr` enum to represent scalars generically

- Removed type from scalar ops ir
- Added new `ScalarIr` enum
- Refactored the related fusion code (now free from generics, and no longer need a special `RelativeOpsScalar`)

Also fixed the dtype for int ops in fusion following int cast support (#3647)

### Testing

Unit tests

### CODE REVIEW

File: crates/burn-ir/src/operation.rs [hunk 1]
```diff
@@ -66,9 +66,9 @@ pub enum OperationIr {
     /// Basic operation on a bool tensor.
     BaseBool(BaseOperationIr),
     /// Numeric operation on a float tensor.
-    NumericFloat(DType, NumericOperationIr<f32>),
+    NumericFloat(DType, NumericOperationIr),
     /// Numeric operation on an int tensor.
-    NumericInt(DType, NumericOperationIr<i32>),
+    NumericInt(DType, NumericOperationIr),
```
Comment (laggui) [inline crates/burn-ir/src/operation.rs:71]: Also, I think numeric ops do not actually need dtype anymore
