### PR TITLE
Fix select vectorization

### LINKED ISSUE #2891: Invalid result of select tensor operation when fusion is enabled.
**Describe the bug**
When using `select` with fusion enabled results are invalid. 

**To Reproduce**
```rust
    #[test]
    fn tensor_select2() {
        type Backend = Wgpu;
        let device = WgpuDevice::DiscreteGpu(1);
        // type Backend = NdArray;
        // let device = NdArrayDevice::Cpu;
        let x1: Tensor<Backend, 4> = Tensor::ones([1, 3, 10, 10], &device);
        let indexes = Tensor::from_data(TensorData::from([1,2,3]), &device);
        println!("Indexes {}", indexes);
        let selected = x1.select(2, indexes.clone()).select(3, indexes);
        println!("Selected {}", selected);

    }
```
```
Indexes Tensor {
  data:
[1, 2, 3],
  shape:  [3],
  device:  DiscreteGpu(1),
  backend:  "fusion<cubecl<wgpu<wgsl>>>",
  kind:  "Int",
  dtype:  "i32",
}
Selected Tensor {
  data:
[[[[1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0]],
  [[0.0, 0.0, 0.0],
   [0.0, 0.0, 0.0],
   [1.0, 1.0, 1.0]],
  [[1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0],
   [0.0, 0.0, 0.0]]]],
  shape:  [1, 3, 3, 3],
  device:  DiscreteGpu(1),
  backend:  "fusion<cubecl<wgpu<wgsl>>>",
  kind:  "Float",
  dtype:  "f32",
}
```
**Expected behavior**
```
Indexes Tensor {
  data:
[1, 2, 3],
  shape:  [3],
  device:  Cpu,
  backend:  "ndarray",
  kind:  "Int",
  dtype:  "i64",
}
Selected Tensor {
  data:
[[[[1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0]],
  [[1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0]],
  [[1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0]]]],
  shape:  [1, 3, 3, 3],
  device:  Cpu,
  backend:  "ndarray",
  kind:  "Float",
  dtype:  "f32",
}
```

**Additional context**
@laggui confirmed that the issue can be reproduced and narrowed it down to fusion being the cause.

### PR DESCRIPTION
**Pull request by nathanielsimard**
fix #2891

### CODE REVIEW

File: crates/burn-tensor/src/tests/ops/select.rs [hunk 1]
```diff
@@ -133,6 +133,22 @@ mod tests {
...
+
+        let first = x1.select(2, indexes.clone());
+        let output = first.select(3, indexes);
+        let expected = TensorData::from([[
+            [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]],
+            [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]],
+            [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]],
+        ]]);
+        output.into_data().assert_eq(&expected, false);
+    }
```
Comment (laggui) [inline crates/burn-tensor/src/tests/ops/select.rs:150]: The input data for this test isn't representative since they're all ones. We're basically making sure that the output is at least written to (no more zeros).

I shared a better test in the linked issue when investigating:

```rust
#[test]
fn should_select_3d_dim1_vec() {
    let device = Default::default();
    let tensor = TestTensor::<3>::from_data(
        [
            [[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0]],
            [[-1.0, -2.0], [-3.0, -4.0], [-5.0, -6.0], [-7.0, -8.0]],
        ],
        &device,
    );
    let indices = TestTensorInt::from_data([1, 0, 3, 2], &device);

    let output = tensor.select(1, indices);
    let expected = TensorData::from([
        [[3.0, 4.0], [1.0, 2.0], [7.0, 8.0], [5.0, 6.0]],
        [[-3.0, -4.0], [-1.0, -2.0], [-7.0, -8.0], [-5.0, -6.0]],
    ]);

    output.into_data().assert_eq(&expected, false);
}
```

This test does not pass on fusion with the current fix.

Output:
```
[[[3.0, 4.0],
  [1.0, 2.0],
  [-7.0, -8.0],
  [-5.0, -6.0]], 
 [[3.0, 4.0],
  [1.0, 2.0],
  [-7.0, -8.0],
  [-5.0, -6.0]]],
```

Expected:
```
[[[3.0, 4.0],
  [1.0, 2.0],
  [7.0, 8.0],
  [5.0, 6.0]],
 [[-3.0, -4.0],
  [-1.0, -2.0],
  [-7.0, -8.0],
  [-5.0, -6.0]]]
```

**Review by laggui — COMMENTED** [review]
We should change the test, the fix is not complete. Will take a look at this in a bit.
